# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='queston_text',
            new_name='question_text',
        ),
    ]
